---
title: "R Notebook"
output: html_notebook
---

The [R plugin](https://www.jetbrains.com/help/pycharm/r-plugin-support.html) for IntelliJ-based IDEs provides
handy capabilities to work with the [R Markdown](https://www.jetbrains.com/help/pycharm/r-markdown.html) files.
To [add](https://www.jetbrains.com/help/pycharm/r-markdown.html#add-code-chunk) a new R chunk,
position the caret at any line or the code chunk, then click "+".

The code chunk appears:
```{r}
library(PASWR)
```


```{r}
zsum.test(mean.x = 100, n.x = 36, sigma.x = 50, mu = 120)
```

```{r}
?pnorm
pnorm(qnorm(0.025, 100, 50/6), 120, 50/6) + 1 - pnorm(qnorm(0.975, 100, 50/6), 120, 50/6)
sigma <- 50
n <- 36
mu0 <- 120
alpha = 0.05
z1 <- 100 + qnorm(0.025) * sigma / sqrt(n)
z2 <- 100 + qnorm(0.975) * sigma / sqrt(n)
pnorm(z1, mu0, sigma / sqrt(n)) + 1 - pnorm(z2, mu0, sigma / sqrt(n))
```

```{r}
mu = 100
mu0 = 120
sigmaX = 50 / 6
alpha = 0.05
z1 = qnorm(alpha / 2, mu, sigmaX)
z2 = qnorm(1 - alpha / 2, mu, sigmaX)
pnorm(z1, mu0, sigmaX) + 1 - pnorm(z2, mu0, sigmaX)
```
```{r}
library(MASS)
data("Rubber")
str(Rubber)

summary(Rubber)
loss <- Rubber$loss
n < length(loss)
meanX <- mean(loss)
varX <- var(loss)
hist(loss)
```
```{r}
t.test(loss, alternative = c("less"), mu = 170)
```
```{r}
?t.test
t.test(vit2005$totalprice, mu = 60000, alternative = "greater")
```

```{r}
binom.test(x = 90, n = 500, p = 0.2)

(0.1473006 + 0.2165364) / 2
```


```{r}
?filter
?subset
greater90 <- subset(x = vit2005, subset = area >= 90)
greater90
v <- var(greater90$totalprice)
v
n <- length(greater90$totalprice)  # n = 94
x <- (n - 1) * v / (60000 * 60000)
qchisq(0.95, n - 1)
```


